[global]
flavor = "mkdocs"
include = ["**/*.md"]
respect-gitignore = true

# Disable rules:
# MD013: Enforces line length
# MD014: Forces commands in codeblocks to show output
disable = ["MD014",]

[per-file-ignores]
"docs/en/how-to/style-guide.md" = ["MD041"]
"docs/en/SUMMARY.md" = ["MD041"]

[MD026]  # Remove punctuation at the end of headings
punctuation = ",;:"

[MD033]  # No inline HTML
allowed_elements = ["nospell",]  # pyspelling inline disable tag

[MD013]  # Line length
line_length = 999999
reflow = true
reflow_mode = "normalize"
