[dependency-groups]
pre-commit = [
    "pre-commit == 4.5.1",
]

tox-uv = [
    "tox-uv == 1.29.0",
]

wlc = [
    "wlc == 1.17.0",
]

dev = [
    {include-group = "pre-commit"},
    {include-group = "tox-uv"},
    {include-group = "wlc"},
]

translate = [
    {include-group = "tox-uv"},
    {include-group = "wlc"},
]

docs = [
    # TODO: Restore main branch for final.
#    "beeware-docs-tools @ git+https://github.com/beeware/beeware-docs-tools",
    "beeware-docs-tools @ git+https://github.com/kattni/beeware-docs-tools@tooling/website-mkdocs-migration",
]

[tool.rumdl]
flavor = "mkdocs"
include = ["**/*.md"]
exclude = ["CODE_OF_CONDUCT.md"]
respect-gitignore = true

# Disable rules:
# MD014: Forces commands in codeblocks to show output
disable = ["MD014",]

[tool.rumdl.per-file-ignores]
"docs/en/how-to/style-guide.md" = ["MD041"]
"docs/en/SUMMARY.md" = ["MD041"]

[tool.rumdl.MD026]  # Remove punctuation at the end of headings
punctuation = ",;:"

[tool.rumdl.MD033]  # No inline HTML
allowed_elements = ["nospell",]  # pyspelling inline disable tag

[tool.rumdl.MD013]  # Line length
line_length = 999999
reflow = true
reflow_mode = "normalize"
